# Generated by Django 4.0.2 on 2022-05-10 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Responsible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование')),
                ('code', models.IntegerField(default=1, verbose_name='Код')),
                ('inv', models.CharField(max_length=50, verbose_name='Инвентарный номер')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('count', models.IntegerField(verbose_name='Количество')),
                ('summ', models.FloatField(verbose_name='Сумма')),
                ('note', models.TextField(max_length=100, verbose_name='Примечание')),
                ('resp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objects', to='inventory_bd.responsible')),
            ],
        ),
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peoples', to='inventory_bd.responsible')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='inventory_bd.responsible')),
            ],
        ),
    ]
