# Generated by Django 4.0.2 on 2022-05-11 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_bd', '0002_thing_delete_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='inventory_bd.thing'),
        ),
    ]
