# Generated by Django 4.0.2 on 2022-05-14 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_bd', '0003_alter_general_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thing',
            name='resp',
        ),
    ]
