# Generated by Django 4.0.2 on 2022-05-18 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_bd', '0006_remove_thing_responsible_thing_responsibles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thing',
            name='responsibles',
        ),
        migrations.AddField(
            model_name='responsible',
            name='things',
            field=models.ManyToManyField(to='inventory_bd.Thing'),
        ),
    ]
