# Generated by Django 4.0.2 on 2022-05-11 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_bd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование')),
                ('code', models.IntegerField(default=1, verbose_name='Код')),
                ('inv', models.CharField(max_length=50, verbose_name='Инвентарный номер')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('count', models.IntegerField(verbose_name='Количество')),
                ('summ', models.FloatField(verbose_name='Сумма')),
                ('note', models.TextField(max_length=100, verbose_name='Примечание')),
                ('resp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='things', to='inventory_bd.responsible')),
            ],
        ),
        migrations.DeleteModel(
            name='Object',
        ),
    ]
