# Generated by Django 4.0.2 on 2022-05-17 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_bd', '0004_remove_thing_resp'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='responsible',
            field=models.ManyToManyField(related_name='things', to='inventory_bd.Responsible'),
        ),
        migrations.DeleteModel(
            name='General',
        ),
    ]
