# Generated by Django 4.0.2 on 2022-05-18 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_bd', '0005_thing_responsible_delete_general'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thing',
            name='responsible',
        ),
        migrations.AddField(
            model_name='thing',
            name='responsibles',
            field=models.ManyToManyField(to='inventory_bd.Responsible'),
        ),
    ]
