# Generated by Django 4.0.2 on 2022-05-18 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_bd', '0007_remove_thing_responsibles_responsible_things'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsible',
            name='things',
            field=models.ManyToManyField(related_name='responsible', to='inventory_bd.Thing'),
        ),
    ]
